# Generated by Django 2.2.1 on 2019-05-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('parent_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(default=None, null=True, to='products.Category')),
            ],
        ),
    ]
