# Generated by Django 2.2.1 on 2019-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(default=None, to='products.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
