# Generated by Django 2.2.1 on 2019-05-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190503_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='products.Category'),
        ),
    ]
